services:
  postgres:
    image: postgres:12.2-alpine
    container_name: gb-db
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432" # Using port from .env file
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  # server:
  #   build: ./server
  #   container_name: server
  #   env_file:
  #     - .env
  #   ports:
  #     - "${PORT}:${PORT}"
  #   depends_on:
  #     - postgres

